//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserAge { get; set; }
        public short DelFlag { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserPwd { get; set; }
        public Nullable<System.DateTime> LastErrorDateTime { get; set; }
        public int ErrorTimes { get; set; }
    }
}
